spring.application.name=allride

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=${MY_ENV_USERNAME}
spring.security.user.password=${MY_ENV_PASSWORD}

spring.jpa.open-in-view=true